### ISSUE TITLE
Exit code -1 only happens when slp is installed

### ISSUE THREAD

**Issue by Atla5De5troyer** [Kotori316/SLP#14]
I've tried different forge versions, different slp versions all come back with exit code -1. I really want to play with advanced generators so I would really like this to work. I tried using the exact same mod setup for these files (AG, bdlib and slp) that another modpack uses (that works fine) and still no success. I know slp is the problem because I tried loading the modpack without it and it loaded fine, apart from the message saying Advanced Generators and Bdlib needing kotori_scala. 

Latest log here:
https://paste-bin.xyz/42111

**Comment by Kotori316** [comment]
Any update for this issue?
How did you solve this?

**Comment by Atla5De5troyer** [comment]
Hi, yh sorry I should've have commented earlier. The problem actually turned out to be from immersive portals not your mod. You're all good, sorry about this.
