### ISSUE TITLE
crash on startup sever with forge 41.1.0

### ISSUE THREAD

**Issue by moidu21** [Kotori316/SLP#20]
[27juil.2022 21:14:03.384] [main/ERROR] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Failed to load mod file META-INF\jarjar\scala-library-2.13.8.jar from ScalableCatsForce-2.13.8-build-6-with-library.jar

that the only line i got from the latest logs (no crash reports) the client work fine

**Comment by Kotori316** [comment]
Confirmed. There is no file provider for JIJ files.

In Client
![file-providers-client](https://user-images.githubusercontent.com/28705167/181422633-71251f96-d412-41a3-8efa-6d988a3c488d.png)

In development Server
![file-providers-server-dev](https://user-images.githubusercontent.com/28705167/181422741-c2b4c232-132b-4ff3-b2bd-11abcc99e5b0.png)

In Server
![file-providers-server](https://user-images.githubusercontent.com/28705167/181422757-78c8a740-3c45-428c-b70e-b67443df1d9f.png)

There are only 4 providers in server instance. So the game crashed.

Solution: Use [old version, 2.13.8-build-4](https://www.curseforge.com/minecraft/mc-mods/scalable-cats-force/files/3759354).

**Comment by Kotori316** [comment]
The server started successfully with Forge 41.0.109, before a change of JIJ is installed.

**Comment by Kotori316** [comment]
MinecraftForge/MinecraftForge#8910
