### ISSUE TITLE
can't make the tanks 

### ISSUE THREAD

**Issue by peanutinky** [Kotori316/SLP#24]
there is no recipe for the tanks in rei so i don't know how im supposed to make the tank when there is no recipe im running fabric on 1.20.1 i see the tanks in the rei just no recipe for the tanks

**Comment by Kotori316** [comment]
This is your environment problem. Just create new environment with Fabric, REI, the tank mod and dependencies, then you can see the recipes on REI(you can also use JEI instead of REI).

One more, this repo is not the right place to post this issue. See https://github.com/Kotori316/FluidTank2
