### ISSUE TITLE
Mincraft Crash

### ISSUE THREAD

**Issue by zodiak246** [Kotori316/SLP#3]
[crash-2020-02-10_18.29.12-client.txt](https://github.com/Kotori316/SLP/files/4183546/crash-2020-02-10_18.29.12-client.txt)

**Comment by Kotori316** [comment]
It seems you have wrong files.
You need https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/download/2871370
Don't download file which has “deobf“ as suffix.
