### ISSUE TITLE
Readme points to a now non-existent file

### ISSUE THREAD

**Issue by porl** [Kotori316/SLP#4]
Hi there
I am trying to work out how to build a mod with your library. Following the Readme.md file, it links to https://github.com/Kotori316/SLP/blob/1.15.2/src/main/resources/META-INF/mods.toml

This file was removed in an earlier commit. I used the old version for reference but still cannot get an empty example mod to work.

Is this readme up to date for the current setup (MC 1.15.2 and Forge 31.2.0)?

Thanks

**Comment by Kotori316** [comment]
Link fixed.

To make scala mods,
1. Download forge mdk and setup the environment.
2. Change `modLoader` and `loaderVersion` in your mods.toml.
3. Download dev jar and place it in mods directory. [Curseforge](https://www.curseforge.com/minecraft/mc-mods/scalable-cats-force/files/2959138) or [GitHub Package](https://github.com/Kotori316/SLP/packages/104937)
4. The make sure Minecraft launches correctly.
5. Then you can add scala classes. Change mod entry class to scala. (if needed)
