### ISSUE TITLE
Build requires symlink in build/classes

### ISSUE THREAD

**Issue by porl** [Kotori316/SLP#5]
Maybe this is from something I missed elsewhere, but in order to build or test a scala mod I must first create a symlink (or copy) from build/classes/scala to build/classes/java, otherwise Forge complains it cant find build/classes/java when trying runClient etc.

Is there some way I can either tell forge that it should look in build/classes/scala or do this automatically?

It would be great if there was a full empty example mod using this library. I tried copying the relevant parts of this mod's code but got the above problem. Having a blank slate that (ideally) could be git cloned and ready to go would be brilliant.

**Comment by Kotori316** [comment]
Add `apply plugin: 'scala'` in your build.gradle. Then gradle will compile codes in `build/classes/scala`.

Wait for template repo.

**Comment by Kotori316** [comment]
https://github.com/Kotori316/SLP-example

**Comment by porl** [comment]
Thanks!
