### ISSUE TITLE
Forge Not Loading If The Library Is In Mod Folder

### ISSUE THREAD

**Issue by LettuceBoi101** [Kotori316/SLP#6]
if the library is out of the folder Minecraft will load but if it is in the mods folder it will not load

the crash occurred in the FML early progress window whilst doing the deep scan on all the mods

error:

The game crashed whilst initializing game
Error: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

Crash Log: [https://pastebin.com/2zP7CF0h](https://pastebin.com/2zP7CF0h)

thank you

**Comment by Kotori316** [comment]
Your crash has no relationship with this library.

You have mistakenly added mods for 1.15.1 even if you're playing 1.16.1.
