### ISSUE TITLE
Crash while loading

### ISSUE THREAD

**Issue by DasHeinzchen** [Kotori316/SLP#9]
When I start Minecraft with this mod (version: 2.13.3-build-6) I will get a crash (circa 2 seconds after starting). There is no crash report or anything. I just get the message "Exit Code: 0"

**Comment by Kotori316** [comment]
Give me log files saved in logs directory. And make sure you have "ScalableCatsForce-2.13.3-build-6-with-library.jar" in your mods directory, not "ScalableCatsForce-2.13.3-build-6-dev.jar"

**Comment by DasHeinzchen** [comment]
Here is the log file:
[latest.log](https://github.com/Kotori316/SLP/files/5665269/latest.log)

**Comment by Kotori316** [comment]
This is not issue related with my mod.

In the latest.log
1. Error occurred applying transform of coremod apothasm/container-repair.js
2. Mixin apply failed upgrade_aquatic.mixins.json

I don't know where the files come from, but you may know and you can ask the authors to fix it.
